name: Install and cache the dependencies
runs:
  using: 'composite'
  steps:
    - name: Cache the node_modules
      uses: actions/cache@v4
      id: cache-deps
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
